services:
  - type: web
    name: ai-blog-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars: []
    rootDir: .
    runtime: node # ✅ Correct field for specifying Node version
